// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DappBoard: typeof import('./src/components/dapp/board.vue')['default']
    DappConnectButton: typeof import('./src/components/dapp/connect-button.vue')['default']
    DappLoader: typeof import('./src/components/dapp/loader.vue')['default']
    DappLogoCoinbaseWallet: typeof import('./src/components/dapp/logo/coinbase-wallet.vue')['default']
    DappLogoMetaMask: typeof import('./src/components/dapp/logo/meta-mask.vue')['default']
    DappLogoWalletConnect: typeof import('./src/components/dapp/logo/WalletConnect.vue')['default']
    DappModal: typeof import('./src/components/dapp/modal.vue')['default']
    FaqItem: typeof import('./src/components/faq/item.vue')['default']
    MainConnect: typeof import('./src/components/main/connect.vue')['default']
    MainFooter: typeof import('./src/components/main/footer.vue')['default']
    MainHeader: typeof import('./src/components/main/header.vue')['default']
    MainMenu: typeof import('./src/components/main/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionAbout: typeof import('./src/components/section/about.vue')['default']
    SectionFounders: typeof import('./src/components/section/founders.vue')['default']
    SectionGoLegendary: typeof import('./src/components/section/go-legendary.vue')['default']
    SectionHero: typeof import('./src/components/section/hero.vue')['default']
    SectionMetaverse: typeof import('./src/components/section/metaverse.vue')['default']
    SectionMutantMushie: typeof import('./src/components/section/mutant-mushie.vue')['default']
    SectionPhunkyFungi: typeof import('./src/components/section/phunky-fungi.vue')['default']
    SectionPremium: typeof import('./src/components/section/premium.vue')['default']
    SectionStakingGame: typeof import('./src/components/section/staking-game.vue')['default']
    StakeToggleButton: typeof import('./src/components/stake/toggle-button.vue')['default']
    SwiperPagination: typeof import('./src/components/swiper-pagination.vue')['default']
  }
}

export {}
